[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "never"

[environment]
NODE_ENV = "production"
PORT = "$PORT"
DATABASE_URL = "$DATABASE_URL"